### ISSUE TITLE
Change alias in configuration file

### ISSUE THREAD

**Issue by KinderGouello** [KinderGouello/syringe#4]
The current way of writing the configuration doesn't allow so much flexibility for the refactoring or to change file namespace. For example with a configuration like this one:

```yaml
parameters:
  mailer.transport: sendmail
services:
  Mailer:
    arguments:
      - "%mailer.transport%"
  NewsletterManager:
    arguments:
      - "@Mailer"
```

the `Mailer` and `NewsletterManager` services are supposed to be in the root of the project, `./Mailer` and `./NewsletterManager`. If we want to move them into a directory of subdirectory, let's say, `folder`, then the configuration file should be like:

```yaml
parameters:
  mailer.transport: sendmail
services:
  "folder/Mailer":
    arguments:
      - "%mailer.transport%"
  "folder/NewsletterManager":
    arguments:
      - "@folder.Mailer"
```

It means that, since the alias of the `Mailer` class changed, then the `NewsletterManager` definition should be updated as well to require a service from a valid alias.

So, with a `path` options required and an alias not auto-generated, you can have much more flexibility to reorganize your code without updating other dependencies.
Here is what it will look like:

```yaml
parameters:
  mailer.transport: sendmail
services:
  mailer: # name chosen by yourself (could be) some.thing.mailer
    path: "folder/Mailer",
    arguments:
      - "%mailer.transport%"
  newsletterManager:
    path: "folder/NewsletterManager",
    arguments:
      - "@mailer"
```

If you move your Mailer class in another directory, then you will only need to update the `path` of the Mailer definition.

You will also be able to declare multiple instances of the same class. Let's say you want different `Mailer` instances that use different kind of transport. The configuration will be:

```yaml
parameters:
  mailer.transport: sendmail
services:
  mailer.basic:
    path: "folder/Mailer",
    arguments:
      - "%mailer.transport%"
  mailer.amazon:
    path: "folder/Mailer",
    arguments:
      - "amazon"
  newsletterManager:
    path: "folder/NewsletterManager",
    arguments:
      - "@mailer.amazon"
```
