### ISSUE TITLE
Add tag support

### ISSUE THREAD

**Issue by KinderGouello** [KinderGouello/syringe#8]
**Describe the solution you'd like**
There are some times where you want to inject automatically some new classes of a same context as a dependency.
For example, you want to inject multiple map API providers into a class to iterate through them:
```typescript
class Map {
  constructor(providers: MapProvider[]) { ... }

  findAllPathEstimations() {
    this.providers.map(...)
  }
}
```

So you will have a configuration like this:
```yaml
services:
  gmap:
    ...
  citymapper:
    ...
  here:
    ...
  map:
    arguments:
      - ['@gmap', '@citymapper', '@here']
      ...
```

This works, but maybe you want to add new providers one day or use this array of map providers for a different use case.
With a `tag` option, you will be able to gather these services into a common group. Then, this group can be provided as an argument and every service with the same tag will be dynamically added to it:

```yaml
services:
  gmap:
    ...
    tags: ['map']
  citymapper:
    ...
    tags: ['map']
  here:
    ...
    tags: ['map']
  map:
    arguments:
      - '#map'
      ...
```

The `#` prefix is dedicated to identifying tag arguments. You can, of course, add multiple tags to a service.
