### ISSUE TITLE
Multiple classes by file

### ISSUE THREAD

**Issue by KinderGouello** [KinderGouello/syringe#9]
**Describe the solution you'd like**
If you have multiple class definitions by file, currently, you will only be able to inject the first class found in that file.
Having a option `class` in the configuration file allows you to have multiple classes in the same file and declare these classes independently in the configuration.
See:

```typescript
// multipleClasses.ts
export class Bar {
  private name: string;

  constructor(name: string) {
    this.name = name;
  }

  getName() {
    return this.name;
  }
}
export class Foo {
  private name: string;

  constructor(name: string) {
    this.name = name;
  }

  getName() {
    return this.name;
  }
}
```

```yaml
services:
  foo:
    path: "multipleClasses"
    class: "Foo"
    arguments:
      - "Foo name"
  bar:
    path: "multipleClasses"
    class: "Bar"
    arguments:
      - "Bar name"
```

**Describe alternatives you've considered**
You could also declare only one class by file.

![](https://media.giphy.com/media/l2SpKR1aR4FMBFQwE/giphy.gif)
